export default [
    {
        username: "businessimperials",
        shortcode: "CzcqNViPUYm",
        age: 0,
        likes: 20,
        views: 100,
        comments: 300,
        id: 0,
    },
    {
        username: "businessimperials",
        shortcode: "CzcK9K-vcaJ",
        age: 1,
        likes: 240,
        views: 324,
        comments: 200,
        id: 1,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 2,
        likes: 0,
        views: 154,
        comments: 100,
        id: 2,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 3,
        likes: 2,
        views: 123,
        comments: 330,
        id: 3,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 4,
        likes: 29,
        views: 4,
        comments: 90,
        id: 4,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 5,
        likes: 1324,
        views: 134,
        comments: 340,
        id: 5,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 6,
        likes: 432,
        views: 342,
        comments: 210,
        id: 6,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 7,
        likes: 40,
        views: 763,
        comments: 30,
        id: 7,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 8,
        likes: 24,
        views: 123,
        comments: 400,
        id: 8,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 9,
        likes: 200,
        views: 0,
        comments: 3760,
        id: 9,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 10,
        likes: 700,
        views: 14,
        comments: 30,
        id: 10,
    },
    {
        username: "businessimperials",
        shortcode: "CzTwZAjvRzf",
        age: 11,
        likes: 800,
        views: 10,
        comments: 3,
        id: 11,
    },
];
